In [154]:
import pandas as pd
import numpy as np
from sklearn import mixture
from sklearn.metrics import *
from sklearn import metrics
import pickle

In [155]:
feature_address=["./test_features/mfcc/timit.hdf","./test_features/mfcc_delta/timit.hdf","./test_features/mfcc_delta_delta/timit.hdf",]

In [156]:
model_address=["./models/mfcc/with/064/",
              "./models/mfcc/without/002/",
              "./models/mfcc/without/004/",
              "./models/mfcc/without/008/",
              "./models/mfcc/without/016/",
              "./models/mfcc/without/032/",
              "./models/mfcc/without/064/",
              "./models/mfcc/without/128/",
              "./models/mfcc/without/256/",
              "./models/mfcc_delta/with/064/",
              "./models/mfcc_delta/without/064/",
              "./models/mfcc_delta_delta/with/064/",
              "./models/mfcc_delta_delta/without/064/",
              ]

In [157]:
#CHANGE FEATURE ADDRESS
df = pd.read_hdf(feature_address[0])
test_features = np.array(df["features"].tolist())
test_labels = np.array(df["labels"].tolist())


In [158]:
features_length=np.shape(test_features)[0]

In [159]:
features_length

451660

In [160]:

def create_models(list_pickle_path):
    gaussian_models={}
    for filename in os.listdir(list_pickle_path):
        if(filename.endswith(".pkl")):
            os.path.join(filename,list_pickle_path)
            file_path = list_pickle_path+str(filename)
            list_unpickle = open(file_path, 'rb')
            gmm = pickle.load(list_unpickle)
            if(filename[:-4]=="none"):
                gaussian_models[gmm]=''
            else:
                gaussian_models[gmm]=filename[:-4]
    return gaussian_models
            

In [161]:
#CHANGE MODEL ADDRESS
gaussian_models=create_models(model_address[0])

In [162]:
def find2(feature_list,gaussian_models):
    M=-10000
    Scores=[]
    Labels=[]
    for model in gaussian_models:
        score=model.score_samples(feature_list)
        Scores.append(score)
        Labels.append(gaussian_models[model])
    return Labels,Scores


In [163]:
Labels,Scores=find2(test_features,gaussian_models)

In [164]:
Scores

[array([-48.07545199, -47.3131402 , -47.08880502, ..., -36.72724597,
        -34.81553679, -34.24783497]),
 array([-49.53800652, -48.30394605, -48.2641104 , ..., -37.0899195 ,
        -33.77615467, -35.24051891]),
 array([-49.97275809, -47.69131049, -48.06173031, ..., -36.93279483,
        -36.10414853, -35.84214211]),
 array([-49.25410249, -48.49170046, -45.49792237, ..., -37.48405798,
        -35.27466283, -34.73366899]),
 array([-49.55720568, -48.49471888, -48.00803439, ..., -36.80470433,
        -34.57120969, -34.53196052]),
 array([-49.05719246, -47.75955273, -47.4305971 , ..., -36.71201626,
        -34.87109735, -34.59338103]),
 array([-49.42799688, -47.97086119, -46.82336839, ..., -37.53553733,
        -33.89956405, -35.53990967]),
 array([-53.64109264, -51.65391994, -48.71070605, ..., -37.84451022,
        -35.00705412, -34.73805703]),
 array([-51.357245  , -48.84397795, -48.0837486 , ..., -41.98271828,
        -41.62813873, -41.27506034]),
 array([-48.84009167, -47.64761928, -

In [165]:
Labels

['ey',
 'ah',
 'ch',
 'ng',
 'er',
 'ih',
 'ay',
 'aw',
 '',
 's',
 't',
 'f',
 'b',
 'aa',
 'uh',
 'g',
 'ow',
 'eh',
 'r',
 'ae',
 'l',
 'k',
 'dh',
 'th',
 'jh',
 'hh',
 'z',
 'sh',
 'm',
 'w',
 'sil',
 'y',
 'n',
 'uw',
 'oy',
 'iy',
 'v',
 'd',
 'dx',
 'p']

In [166]:
def f(features_length,features_scores,labels):
    Predictions=[]
    for i in range(features_length):
        Max=features_scores[0][i]
        label=labels[0]
        for j in range(len(labels)):
            s=features_scores[j][i]
            if(s>Max):
                Max=s
                label=labels[j]
        Predictions.append(label)
    
    return Predictions

In [167]:
Prediction_Labels=f(features_length,Scores,Labels)

In [168]:
metrics.accuracy_score(Prediction_Labels,test_labels)

0.14368551565336757